FROM mcr.microsoft.com/mssql/server:2022-latest

USER root

# Install required dependencies and mssql-tools
RUN if ! dpkg-query -l | grep -q "mssql-tools"; then \
    apt-get update && apt-get install -y \
    gnupg \
    curl \
    apt-transport-https \
    unixodbc-dev \
    && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && ACCEPT_EULA=Y apt-get install -y mssql-tools \
    && rm -rf /var/lib/apt/lists/*; \
    fi

# Set the environment variable for the MSSQL server
ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=@@devcode3231

# Expose SQL Server port
EXPOSE 1433

# Start SQL Server
CMD /opt/mssql/bin/sqlservr
